### ISSUE TITLE
Program not work on C# ?

### ISSUE THREAD

**Issue by Dentrax** [Samjayyy/logicpuzzles#1]
Hello,
I converted this code to C#, but not work. Can you help me for this ?

http://txs.io/kqPb
txs(dot)io(slash)kqPb
Thanks...

**Comment by Samjayyy** [comment]
What's not working? I have little time at the moment to do some debugging.
But by a quick peek I see your hashcode method is missing on the Block class. 

This will make finding duplicates fail.

**Comment by Dentrax** [comment]
Hello Again,

I fixed code, now its working with duplicate fail. But when used hashcode, its missing some block. (same too original code, its fully top/left, its missing some blocks.) I could not solve this problem with for loop. Thx... 
http://en.textsave.org/frPb
en(dot)textsave(dot)org(slash)frPb

**Comment by Samjayyy** [comment]
You need a hashcode implementation that uses the contents. And not based on the array adress.
For example:

```
    public override int GetHashCode()
    {
        int hc = rows.Length;
        for (int i = 0; i < rows.Length; ++i)
        {
            hc = unchecked(hc * 314159 + rows[i]);
        }
        return hc;
    }
```

This fixes it. Full Code: http://txs.io/msPb

Kr,
Sam

**Comment by Dentrax** [comment]
Thank you, but you can't understand me. Wıth GetHashCode() not work properly. Because only show horizontal blocks not all. I need vertical and horizontal blocks.Like this (with duplicate fail) ;

-How can remove duplicate fail ?

http://en.textsave.org/xsPb

http://i.hizliresim.com/QZlq6v.png

```
  public override int GetHashCode()
    {
        int rl = rows.Length;
        for (int i = 0; i < rows.Length; ++i)
        {
            rl = unchecked(rl * 1907 + rows[i]);
        }

        return rl;
    }


    public override bool Equals(object obj)
    {
        Block b = (Block)obj; 
        //return this.size == b.size && Enumerable.SequenceEqual(this.rows, b.rows);         
        return this == b;
    }
```

**Comment by Samjayyy** [comment]
You are pretty hard to understand. Please try to explain what you want and give exact examples.
Also try to use correct english. As far as I understand now, I think you want all unique rotations of the blocks. You can do this by using the `rotate` method on the resulting blocks.

For example change the `allBlocks` method like this:

```
    public string allBlocksWithRotations()
    {
        StringBuilder sb = new StringBuilder();
        foreach (Block b in list)
        {
            Block b1 = b;
            do
            {
                sb.Append(b1.ToString());
                sb.Append("_______________\n");
                b1 = b1.rotate();
            } while (!b.Equals(b1));
        }
        return sb.ToString();
    }
```

**Comment by Dentrax** [comment]
Oh, sorry for bad english. Thank you for answer. The last problem, how can i the  fix ToString() method ?

N=3; Old ToString() -> 2 different bloks, Need to New ToString() for allBlocksWithRotations() : should be 6.

This is not working:
if (!list.Contains(b1))
                {
                    Console.WriteLine("ADDED");
                    list.AddLast(b1);
                }

Thx again...

**Comment by Samjayyy** [comment]
Why don't you just count the number of times a block is printed out?

```
    public string allBlocksWithRotations()
    {
        StringBuilder sb = new StringBuilder();
        var count = 0;
        foreach (Block b in list)
        {
            Block b1 = b;
            do
            {
                count++;
                sb.Append(b1.ToString());
                sb.Append("_______________\n");
                b1 = b1.rotate();
            } while (!b.Equals(b1));
        }
        sb.Append("There are "+count+" blocks of size "+currentSize+" (rotations inclusive)\n");
        return sb.ToString();
    }
```
